#!/bin/bash
ln -sf /bin/stobe/Basis/baslib.new7 fort.3
ln -sf /bin/stobe/Basis/symbasis.new fort.4
cat >C1gnd.inp<</.
TITLE
minimal GND
SYMMETRY C1
CARTESIAN ANGSTROMS
C       0.000000      0.000000      0.000000     6     32
C       1.500000      0.000000      0.000000     4     32
END
RUNTYPE startup nooptimize
SCFTYPE direct
POTENTIAL nonlocal rpbe pbe
GRID fine
MULTIPLICITY 1
CHARGE 0
MAXCYCLES 300
ECONVERGENCE 0.001
DCONVERGENCE 0.001
DMIXING mdens 0.05
DIIS new 7
ORBI 5d
MULLIKEN on full
VIRT all
SPIN FULL
FSYM scfocc
ALFA 8
BETA 8
FILE molden
END
A-CARBON (5,2;5,2)
A-CARBON(+4) (3,3;3,3)
O-CARBON iii_iglo
O-CARBON(+4) (311/211/1)
P-CARBON(+4) (3,1:8,0)
P-CARBON(+4) (3,1:8,0)
X-FIRST
END
/.
mkdir -p ../GND
StoBe.x <C1gnd.inp>& ../GND/C1gnd.out
mv Molden.molf ../GND/C1gnd.molden
rm fort.*
