"""Generate ``molConfig.py`` modules for StoBe ``dftrun build``."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from dftlearn.setup.basis_sets import stobe_basis_for_element

if TYPE_CHECKING:
    from dftlearn.setup.types import InitGeometryPlan

UNASSIGNED_ALFA_OCC = "0 0 0 0.0"
UNASSIGNED_ALFA_OCC_TP = "0 0 0 0.0"


def valence_electron_count(plan: InitGeometryPlan) -> int:
    """Count electrons in the StoBe valence SCF, including MCP spectators.

    Nuclear charges in the input are not the all-electron sum when the
    core-edge element uses a model core potential on every carbon except the
    absorber. Spectator atoms contribute ``z_eff_excited`` (typically 4 for
    ``P-CARBON(+4)``), and the absorber contributes ``z_eff_ground``. Other
    elements contribute their full atomic numbers.

    Parameters
    ----------
    plan : InitGeometryPlan
        Geometry with ``element_counts`` and ``edge_element``.

    Returns
    -------
    int
        Total valence electrons implied by the effective nuclear charges.

    Raises
    ------
    KeyError
        If an element in ``plan.element_counts`` has no StoBe basis preset.
    """
    total = 0
    edge = plan.edge_element.strip().capitalize()
    for sym, count in plan.element_counts.items():
        preset = stobe_basis_for_element(sym)
        key = sym.strip().capitalize()
        if key == edge and preset.mcp and count > 0:
            total += preset.z_eff_ground + preset.z_eff_excited * (count - 1)
        else:
            total += preset.atomic_number * count
    return total


def render_molconfig_py(
    *,
    fname: str,
    mname: str,
    plan: InitGeometryPlan,
) -> str:
    """Render a ``molConfig.py`` source string from a geometry plan.

    Parameters
    ----------
    fname
        XYZ stem written by init (typically ``geometry``).
    mname
        Molecule title embedded in StoBe ``TITLE`` keywords.
    plan
        Ordered geometry and element counts.

    Returns
    -------
    str
        Python source for ``molConfig.py`` consumable by ``dftrun build``.

    Raises
    ------
    ValueError
        If the MCP-aware valence electron count is odd, so a closed-shell
        alpha/beta split is undefined.
    """
    edge = plan.edge_element
    n_files = len(plan.generating_site_indices)
    element_order = plan.element_group_order
    dif_elems = len(element_order)

    elem_counts = [plan.element_counts.get(sym, 0) for sym in element_order]
    while len(elem_counts) < 6:
        elem_counts.append(0)

    stobe_basis_for_element(edge)
    total_e = valence_electron_count(plan)
    if total_e % 2 != 0:
        msg = (
            f"Valence electron count {total_e} is odd; closed-shell "
            "alpha/beta occupations are undefined"
        )
        raise ValueError(msg)
    half = total_e // 2

    lines: list[str] = [
        "# Generated by dftrun init",
        f'fname = "{fname}"',
        f'mname = "{mname}"',
        f'aname = "{edge}"',
        f"nFiles = {n_files}",
        f"difElems = {dif_elems}",
    ]

    for idx in range(1, 7):
        if idx <= len(element_order):
            sym = element_order[idx - 1]
            preset = stobe_basis_for_element(sym)
            if sym == edge:
                lines.append(f"element{idx}a = {preset.z_eff_ground}")
                lines.append(f"element{idx}b = {preset.z_eff_excited}")
            else:
                lines.append(f"element{idx} = {preset.atomic_number}")
        else:
            lines.append(f"element{idx} = 0" if idx > 1 else f"element{idx}a = 0")

    for idx, count in enumerate(elem_counts[:6], start=1):
        lines.append(f"nElem{idx} = {count}")

    for idx in range(1, 7):
        if idx <= len(element_order):
            sym = element_order[idx - 1]
            preset = stobe_basis_for_element(sym)
            if sym == edge:
                lines.append(f'elem{idx}_Abasis_a = "{preset.aux_ground}"')
                lines.append(f'elem{idx}_Abasis_b = "{preset.aux_excited}"')
                lines.append(f'elem{idx}_Obasis_a = "{preset.orbital_ground}"')
                lines.append(f'elem{idx}_Obasis_b = "{preset.orbital_excited}"')
                if preset.mcp:
                    lines.append(f'elem{idx}_MCPbasis = "{preset.mcp}"')
            else:
                lines.append(f'elem{idx}_Abasis = "{preset.aux_ground}"')
                lines.append(f'elem{idx}_Obasis = "{preset.orbital_ground}"')
        else:
            lines.append(f'elem{idx}_Abasis = ""')
            lines.append(f'elem{idx}_Obasis = ""')

    lines.extend(
        [
            f"alpha = {half}",
            f"beta = {half}",
            f'alfaOcc = "{UNASSIGNED_ALFA_OCC}"',
            'betaOcc = "0 0"',
            f'alfaOccTP = "{UNASSIGNED_ALFA_OCC_TP}"',
            "sym = None",
            "geom = None",
            'multiplicity = "1"',
            "charge = None",
            "potential = None",
            "noFSsym = None",
            "fsymGND = None",
            "fsymEXC = None",
            "smear = None",
            "conf = None",
            "exci = None",
            "field = None",
            "spin = None",
            "reorder = None",
            "localize = None",
            "runtype = None",
            "scftype = None",
            "maxcycles = None",
            "econvergence = None",
            "dconvergence = None",
            "dmixing = None",
            "diis = None",
            "levelshift = None",
            "maxoverlap = None",
            "integration = None",
            "grid = None",
            "wedge = None",
            "slater = None",
            "ptcharges = None",
            "bsserror = None",
            "supsym = None",
            "trrh = None",
            "gconvergence = None",
            "gstepsize = None",
            "maxgeometries = None",
            "coordinate = None",
            "atom = None",
            "group = None",
            "hessian = None",
            "gradients = None",
            "strbalsac = None",
            "mulliken = None",
            "lowedin = None",
            "mepfit = None",
            "balpop = None",
            "draw = None",
            "pscratch = None",
            "xrayspec = None",
            "topological = None",
            "nmrout = None",
            "eprout = None",
            "vibrations = None",
            "nebparams = None",
            "resinput = None",
            "resoutput = None",
            "title = mname",
            "printout = None",
            "save = None",
            "orbi = None",
            "ecpread = None",
            "pntgen = None",
            "alchem = None",
            "mofile = None",
            "virt = None",
            "ctrlopt = None",
            "dosout = None",
            "shortres = None",
            "forces = None",
            "dynamics = None",
            "geoformat = None",
        ]
    )
    return "\n".join(lines) + "\n"


def write_molconfig_py(path: Path, source: str) -> None:
    """Write rendered ``molConfig.py`` source to ``path``."""
    Path(path).write_text(source, encoding="utf-8")
